# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d09201d7eacf38b68343f8be6a8fb8c2da796672793d31d23da290eb125b42c96daa0da823fe39ebe7378d27bff3cee84ec12fc69c883de02a88c578b750ec6a

test:
  secret_key_base: fbd57c889c0b6ae9ad14d7a35efaf3bd2301ae282e972130064606dc3465896a865f98463fd2733be460c1ce8d570726a918c14a706abe55544126f4dabf42cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
